name: Build Nuxt.js
on: [push]

jobs:
  build-nuxtjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Add ignored files
        run: |
          cd ${{ github.workspace }}
          echo "{\"password\":\"GitHub_@ctions\"}" > server/admin.json
      - name: Build the project
        run: npm run build