name: Upload Release
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
    upload-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Build Nuxt.js project
              run: |
                cd ${{ github.workspace }}
                echo "{\"password\":\"GitHub_@ctions\"}" > server/admin.json
                FILE="Files-$(date +%Y-%m-%d).zip"
                npm run build && zip -r "$FILE" .output/*
                curl -X POST https://files.lumaa.fr/api/upload \
                    -H "Authorization: ${{ secrets.LUMAA_FILES_PASS }}" \
                    -F "file=@$FILE"